import React, { useState } from 'react';
import CustomerPortal from './Components/CustomerPortal';
import AdminDashboard from './Components/AdminDashboard';
import Home from './Components/Home';
import Header from './Components/Header';
import { FANS_DATA } from './data/fans'; 


const App = () => {
  const [view, setView] = useState('home');
  const [fans, setFans] = useState(FANS_DATA);

  const handleUpdateFan = (updatedFan) => {
    setFans(prevFans => prevFans.map(fan => fan.id === updatedFan.id ? updatedFan : fan));
  };

  const handleAddFan = (newFan) => {
    // In a real app, ID would be generated by the backend. Here we use timestamp.
    const fanWithId = { ...newFan, id: Date.now() };
    setFans(prevFans => [...prevFans, fanWithId]);
  };

  const handleAddFansBatch = (newFans) => {
    const fansWithIds = newFans.map((fan, index) => ({
      ...fan,
      id: Date.now() + index, // Ensure unique IDs for the batch
    }));
    setFans(prevFans => [...prevFans, ...fansWithIds]);
  };

  const handleDeleteFan = (fanId) => {
    // In a real app, you would likely soft delete or archive.
    setFans(prevFans => prevFans.filter(fan => fan.id !== fanId));
  };

  const renderContent = () => {
    switch (view) {
      case 'customer':
        return <CustomerPortal fans={fans} />;
      case 'admin':
        return (
          <AdminDashboard 
            fans={fans}
            onAddFan={handleAddFan}
            onUpdateFan={handleUpdateFan}
            onDeleteFan={handleDeleteFan}
            onAddFansBatch={handleAddFansBatch}
          />
        );
      case 'home':
      default:
        return <Home onNavigate={setView} />;
    }
  };

  return (
    <div className="bg-slate-100 min-h-screen text-slate-800 flex flex-col justify-center w-full ">
      <Header showHomeButton={view !== 'home'} onGoHome={() => setView('home')} />
      <main className="w-full p-4 md:p-8">
        {renderContent()}
      </main>
      <footer className="text-center p-4 text-slate-500 text-sm no-print">
        <p>طراحی شده توسط مهندس ارشد فرانت‌اند با تخصص در React و Gemini API</p>
      </footer>
    </div>
  );
};

export default App;
